dataloader:
  class: "torch.utils.data.DataLoader"
  batch_size: 10
  shuffle: False
  dataset:
    class: "grconvnet.dataloading.YCBSimulationData"
    root_dir: "/home/moritz/Documents/ycb_sim_data_1"
    transform:
      class: "grconvnet.preprocessing.Preprocessor"
      intermediate_results_queue_size: 10
      reformatter:
        class: "grconvnet.preprocessing.CenterCropResized"
        size: [224, 224]
      masker:
        class: "grconvnet.preprocessing.Masker"
        negative_value: [255, 255, 255]
        positive_value: [0, 0, 0]

model:
  class: "grconvnet.models.GenerativeResnet"
  constructor: "from_jit"
  jit_path: "cornell-randsplit-rgbd-grconvnet3-drop1-ch32/epoch_15_iou_97.pt"
  device: "cuda"

postprocessor:
  class: "grconvnet.postprocessing.Postprocessor"
  intermediate_results_queue_size: 10
  q_blurrer:
    class: "grconvnet.postprocessing.SkGaussian"
    sigma: 2
  angle_blurrer:
    class: "grconvnet.postprocessing.SkGaussian"
    sigma: 2
  width_blurrer:
    class: "grconvnet.postprocessing.SkGaussian"
    sigma: 1
  width_scaler:
    class: "grconvnet.postprocessing.Scaler"
    factor: 150
  grasp_localizer:
    class: "grconvnet.postprocessing.GraspLocalizer"
    min_distance: 20
    threshold: 0.2
    n_grasps: 3

img2world_converter:
  class: "grconvnet.postprocessing.Img2WorldConverter"
  coord_converter:
    class: "grconvnet.postprocessing.Img2WorldCoordConverter"
  decropper:
    class: "grconvnet.postprocessing.DeCenterCropResized"
  height_adjuster:
    null
    # class: "grconvnet.postprocessing.GraspHeightAdjuster"
    # min_height: 0.01
    # target_grasp_depth: 0.04

exporter:
  class: "grconvnet.utils.export.Exporter"
  export_dir: "/home/moritz/Documents/GrConvNetBenchmark/grconvnet/data/results/ycb_sim_data_1_no_height"
